trello:
  developer_public_key: <here put the key taken from https://trello.com/1/appKey/generate>
  access_token_key: <here put the token taken in the 'Reading Private Data' section from https://trello.com/1/appKey/generate>

tracker_username: <here put the Trello member used as recipient of the tracking notifications>
google_docs_username: <here put your Google Docs username>